### ISSUE TITLE
Images are overflowing

### ISSUE THREAD

**Issue by YeonjuSeo** [splitbee/react-notion#77]
I'm trying to render one notion page. 
Font size is fine but the images are getting bigger than the wrapper and the layout isn't working properly.  I don't know what to do Plz help me.

This is the notion page: 
![image](https://user-images.githubusercontent.com/56028436/128163405-fde8f720-18ea-49e1-ba64-21a3a7718ae1.png)

And this is the react-notion page:
![스크린샷 2021-08-04 19 08 36](https://user-images.githubusercontent.com/56028436/128163688-de9ba040-f40d-4070-b0e9-34324b2655a8.png)<br/>
![image](https://user-images.githubusercontent.com/56028436/128164573-9a705ace-26e1-4c4a-b4a6-8da700117764.png)

This is my code: 

```Javascript
<StyledNotionWrapper>
{isNotionContent && <NotionRenderer blockMap={notionData} />}
</StyledNotionWrapper>

const StyledNotionWrapper = styled.div`
	width: 792px;
	max-width: 792px;
	font-size: 0.2rem;
`;
```

**Comment by dimitrisraptis96** [comment]
These CSS classes fixed the issue for me @YeonjuSeo : 

```css
.notion,
.notion img,
.notion-asset-wrapper {
  max-width: 100%;
}
.notion-asset-wrapper > div {
  padding-bottom: 0 !important;
}
```
